# Generated by Django 2.2.1 on 2019-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=78)),
                ('temperature', models.IntegerField(default=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
