# Generated by Django 2.2.1 on 2019-05-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_hackathon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='distance',
            field=models.FloatField(default=3.5),
        ),
    ]
